Installez pg et pg-hstore

npm install pg pg-hstore

Installez dotenv pour gérer les variables d'environnement :

npm install dotenv


Créez un fichier .env.local à la racine de votre projet et ajoutez vos informations de connexion à la base de données :

DATABASE_URL=postgres://username:password@localhost:5432/mydatabase

Remplacez username et password par vos informations d'identification PostgreSQL.


Créez un dossier lib à la racine de votre projet et un fichier db.js à l'intérieur :

const { Pool } = require('pg');
require('dotenv').config();

const pool = new Pool({
    connectionString: process.env.DATABASE_URL,
});

module.exports = {
    query: (text, params) => pool.query(text, params),
};


//Cree ensuite tes API pour tester la connexion