import { WORKSPACE_ROLES, WorkspaceRole } from "./roles";

export const PERMISSIONS = {
   ANNOUNCEMENT_READ: "announcement:read",
   ANNOUNCEMENT_CREATE: "announcement:create",
   ANNOUNCEMENT_UPDATE: "announcement:update",
   ANNOUNCEMENT_DELETE: "announcement:delete",
   BILLING_READ: "billing:read",
   BILLING_MANAGE: "billing:manage",
   MEMBER_MANAGE: "member:manage",
   FEATURE_FLAG_MANAGE: "feature-flag:manage",
   AUDIT_LOG_READ: "audit-log:read",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const WORKSPACE_ROLE_PERMISSIONS: Record<WorkspaceRole, Permission[]> = {
   [WORKSPACE_ROLES.OWNER]: Object.values(PERMISSIONS),
   [WORKSPACE_ROLES.ADMIN]: [
      PERMISSIONS.ANNOUNCEMENT_READ,
      PERMISSIONS.ANNOUNCEMENT_CREATE,
      PERMISSIONS.ANNOUNCEMENT_UPDATE,
      PERMISSIONS.ANNOUNCEMENT_DELETE,
      PERMISSIONS.BILLING_READ,
      PERMISSIONS.MEMBER_MANAGE,
      PERMISSIONS.FEATURE_FLAG_MANAGE,
      PERMISSIONS.AUDIT_LOG_READ,
   ],
   [WORKSPACE_ROLES.MEMBER]: [
      PERMISSIONS.ANNOUNCEMENT_READ,
      PERMISSIONS.ANNOUNCEMENT_CREATE,
      PERMISSIONS.ANNOUNCEMENT_UPDATE,
   ],
   [WORKSPACE_ROLES.VIEWER]: [PERMISSIONS.ANNOUNCEMENT_READ],
};
